<?php
// Bilingual dictionary (English + Hindi) for PUBLIC pages
// Admin console remains English.

function lang(): string {
    if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'hi'], true)) {
        $_SESSION['lang'] = $_GET['lang'];
    }
    return $_SESSION['lang'] ?? 'en';
}

function t(string $key): string {
    static $D = null;
    if ($D === null) {
        $D = [
            'en' => [
                'gov_in' => 'GOVERNMENT OF INDIA', 'gov_in_hi' => 'भारत सरकार',
                'mod' => 'Ministry of Defence · Public Sector Undertaking',
                'brand' => 'Bharat Electronics Limited',
                'brand_unit' => 'KOTDWAR · ASSESSMENT PORTAL',
                'system_online' => 'System Online',
                'lang_toggle' => 'हिंदी',
                'bar_portal' => 'ONLINE EXAMINATION & ASSESSMENT PORTAL · BEL KOTDWAR UNIT',
                'hero_title' => 'Secure online assessment, built for BEL Kotdwar.',
                'hero_sub' => 'Conduct fair, lockdown-secured exams for candidates and trainees with proctoring, violation logs, and instant evaluation — exactly like a real test centre.',
                'cta_student' => 'Candidate / Student Login',
                'cta_admin' => 'Administrator Login',
                'cta_note' => 'New candidates do not register here. Accounts are issued by the BEL administrator.',
                'about_h' => 'About Bharat Electronics Limited',
                'about_p1' => 'Bharat Electronics Limited (BEL) is a Navratna Public Sector Undertaking under the Ministry of Defence, Government of India, established in 1954 and headquartered in Bengaluru.',
                'about_p2' => 'BEL has nine manufacturing units across India — Bengaluru, Ghaziabad, Pune, Hyderabad, Machilipatnam, Chennai, Panchkula, Navi Mumbai and Kotdwar (Uttarakhand).',
                'quick_facts' => 'Quick Facts',
                'feat1_h' => 'Lockdown Browser', 'feat1_t' => 'Fullscreen, tab-switch detection, copy/paste blocked, auto-submit on repeated violations.',
                'feat2_h' => 'Live Proctoring', 'feat2_t' => 'Webcam preview and time-stamped violation logs visible to administrators.',
                'feat3_h' => 'Audit Trail', 'feat3_t' => 'Every answer and event is timestamped. Reviewers see what was selected and when.',
                'footer_auth' => 'For authorised use only · सर्वाधिकार सुरक्षित',
                'footer_enterprise' => 'A Government of India Enterprise · Kotdwar Unit',
                'sl_title' => 'Candidate Login', 'sl_sub' => 'Login using your Roll Number / Staff ID, Date of Birth, and password.',
                'sl_id' => 'Roll Number / Staff ID', 'sl_dob' => 'Date of Birth', 'sl_pwd' => 'Password',
                'sl_submit' => 'Sign In', 'sl_back' => 'Back', 'sl_forgot' => 'Forgot password?',
                'al_title' => 'Administrator Login', 'al_sub' => 'Restricted — for BEL Kotdwar exam administrators only.',
                'al_id' => 'Email',
                'sd_title' => 'Available Examinations', 'sd_sub' => 'Read the instructions carefully before starting any exam.',
                'sd_my_results' => 'My Results', 'sd_logout' => 'Logout',
                'sd_duration' => 'Duration', 'sd_questions' => 'Questions', 'sd_attempts_left' => 'Attempts left',
                'sd_view_instructions' => 'View Instructions', 'sd_welcome' => 'Welcome',
                'sd_closed' => 'Closed', 'sd_upcoming' => 'Upcoming', 'sd_active' => 'Active',
                'sd_no_exams' => 'No exams scheduled yet.',
                'in_title' => 'Examination Instructions', 'in_begin' => 'Confirm & Begin Exam',
                'in_agree' => 'I have read all instructions and understand violations will be recorded.',
                'rs_title' => 'My Results', 'rs_exam' => 'Exam', 'rs_attempt' => 'Attempt', 'rs_score' => 'Score', 'rs_submitted' => 'Submitted', 'rs_none' => 'No attempts yet.',
                'fg_title' => 'Forgot Password', 'fg_get' => 'Get Reset Token', 'fg_reset' => 'Reset Password',
                'fg_token' => 'Reset Token', 'fg_newpwd' => 'New Password (min 6)',
                // ----- Take-Exam screen (offline, no Google Translate) -----
                'ex_attempt' => 'Attempt', 'ex_question' => 'Question', 'ex_marks' => 'marks',
                'ex_start_fs_title' => 'Start in Fullscreen',
                'ex_start_fs_hint' => 'Click the button below to enter fullscreen and begin the lockdown exam session.',
                'ex_start_fs_btn' => 'Enter Fullscreen & Start Exam',
                'ex_live' => 'LIVE',
                'ex_prev' => 'Previous', 'ex_mark' => 'Mark for Review', 'ex_unmark' => 'Unmark Review',
                'ex_save_next' => 'Save & Next', 'ex_submit' => 'Submit',
                'ex_palette' => 'Question Palette',
                'ex_answered' => 'Answered', 'ex_not_answered' => 'Not Ans.',
                'ex_marked' => 'Marked', 'ex_ans_marked' => 'Ans+Mark',
                'ex_lang_en' => 'English', 'ex_lang_hi' => 'हिंदी',
                'ex_lang_label' => 'Language',
                'ex_translate_q' => 'Show in हिंदी', 'ex_translate_q_back' => 'Show in English',
                'ex_submit_confirm' => 'Are you sure you want to submit the exam? You cannot change answers after submitting.',
                'ex_violation' => 'Violation detected — this is being recorded.',
                'ex_qtype_mcq' => 'Multiple Choice', 'ex_qtype_multi' => 'Multi Select',
                'ex_qtype_tf' => 'True / False', 'ex_qtype_sa' => 'Short Answer', 'ex_qtype_num' => 'Numeric',
                'ex_true' => 'True', 'ex_false' => 'False',
                'ex_no_hi' => '(Hindi translation not available for this question)',
            ],
            'hi' => [
                'gov_in' => 'भारत सरकार', 'gov_in_hi' => 'GOVERNMENT OF INDIA',
                'mod' => 'रक्षा मंत्रालय · सार्वजनिक उपक्रम',
                'brand' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड',
                'brand_unit' => 'कोटद्वार · मूल्यांकन पोर्टल',
                'system_online' => 'सिस्टम ऑनलाइन',
                'lang_toggle' => 'English',
                'bar_portal' => 'ऑनलाइन परीक्षा एवं मूल्यांकन पोर्टल · BEL कोटद्वार इकाई',
                'hero_title' => 'BEL कोटद्वार के लिए सुरक्षित ऑनलाइन मूल्यांकन।',
                'hero_sub' => 'अभ्यर्थियों व प्रशिक्षुओं के लिए लॉकडाउन-सुरक्षित परीक्षा, प्रॉक्टरिंग, उल्लंघन लॉग और तत्काल मूल्यांकन।',
                'cta_student' => 'अभ्यर्थी / विद्यार्थी लॉगिन',
                'cta_admin' => 'प्रशासक लॉगिन',
                'cta_note' => 'नए अभ्यर्थी यहाँ पंजीकरण नहीं करते। खाते BEL प्रशासक द्वारा जारी किए जाते हैं।',
                'about_h' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड के बारे में',
                'about_p1' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड (BEL) भारत सरकार के रक्षा मंत्रालय के अधीन नवरत्न सार्वजनिक उपक्रम है, स्थापना 1954, मुख्यालय बेंगलुरु।',
                'about_p2' => 'BEL की भारत में नौ विनिर्माण इकाइयाँ हैं — बेंगलुरु, गाज़ियाबाद, पुणे, हैदराबाद, मछलीपट्टनम, चेन्नई, पंचकुला, नवी मुंबई तथा कोटद्वार।',
                'quick_facts' => 'मुख्य तथ्य',
                'feat1_h' => 'लॉकडाउन ब्राउज़र', 'feat1_t' => 'पूर्ण स्क्रीन, टैब-स्विच पहचान, कॉपी/पेस्ट निष्क्रिय, उल्लंघन पर स्वतः जमा।',
                'feat2_h' => 'लाइव प्रॉक्टरिंग', 'feat2_t' => 'वेबकैम व समय-मुद्रित उल्लंघन लॉग प्रशासकों हेतु।',
                'feat3_h' => 'ऑडिट ट्रेल', 'feat3_t' => 'प्रत्येक उत्तर व घटना समय-मुद्रित।',
                'footer_auth' => 'केवल अधिकृत उपयोग हेतु · सर्वाधिकार सुरक्षित',
                'footer_enterprise' => 'भारत सरकार का उपक्रम · कोटद्वार इकाई',
                'sl_title' => 'अभ्यर्थी लॉगिन', 'sl_sub' => 'अपनी रोल/स्टाफ़ आईडी, जन्म तिथि तथा पासवर्ड से लॉगिन करें।',
                'sl_id' => 'रोल/स्टाफ़ आईडी / उपयोगकर्ता नाम', 'sl_dob' => 'जन्म तिथि', 'sl_pwd' => 'पासवर्ड',
                'sl_submit' => 'लॉगिन करें', 'sl_back' => 'वापस', 'sl_forgot' => 'पासवर्ड भूल गए?',
                'al_title' => 'प्रशासक लॉगिन', 'al_sub' => 'प्रतिबंधित क्षेत्र — केवल BEL प्रशासकों हेतु।',
                'al_id' => 'ईमेल / उपयोगकर्ता नाम',
                'sd_title' => 'उपलब्ध परीक्षाएँ', 'sd_sub' => 'कोई भी परीक्षा शुरू करने से पहले निर्देश ध्यानपूर्वक पढ़ें।',
                'sd_my_results' => 'मेरे परिणाम', 'sd_logout' => 'लॉगआउट',
                'sd_duration' => 'अवधि', 'sd_questions' => 'प्रश्न', 'sd_attempts_left' => 'शेष प्रयास',
                'sd_view_instructions' => 'निर्देश देखें', 'sd_welcome' => 'स्वागत है',
                'sd_closed' => 'बंद', 'sd_upcoming' => 'आगामी', 'sd_active' => 'सक्रिय',
                'sd_no_exams' => 'अभी कोई परीक्षा निर्धारित नहीं है।',
                'in_title' => 'परीक्षा निर्देश', 'in_begin' => 'पुष्टि करें व प्रारंभ करें',
                'in_agree' => 'मैंने सभी निर्देश पढ़ लिए हैं और समझता/समझती हूँ कि उल्लंघन दर्ज किए जाएँगे।',
                'rs_title' => 'मेरे परिणाम', 'rs_exam' => 'परीक्षा', 'rs_attempt' => 'प्रयास', 'rs_score' => 'अंक', 'rs_submitted' => 'जमा किया', 'rs_none' => 'अभी कोई प्रयास नहीं।',
                'fg_title' => 'पासवर्ड भूल गए', 'fg_get' => 'रीसेट टोकन प्राप्त करें', 'fg_reset' => 'पासवर्ड रीसेट करें',
                'fg_token' => 'रीसेट टोकन', 'fg_newpwd' => 'नया पासवर्ड (न्यूनतम 6)',
                // ----- परीक्षा स्क्रीन (ऑफ़लाइन / इंट्रानेट के लिए) -----
                'ex_attempt' => 'प्रयास', 'ex_question' => 'प्रश्न', 'ex_marks' => 'अंक',
                'ex_start_fs_title' => 'पूर्ण स्क्रीन में प्रारंभ करें',
                'ex_start_fs_hint' => 'परीक्षा प्रारंभ करने के लिए नीचे दिए बटन पर क्लिक करें और पूर्ण स्क्रीन में प्रवेश करें।',
                'ex_start_fs_btn' => 'पूर्ण स्क्रीन में जाएँ और परीक्षा प्रारंभ करें',
                'ex_live' => 'लाइव',
                'ex_prev' => 'पिछला', 'ex_mark' => 'समीक्षा हेतु चिह्नित करें', 'ex_unmark' => 'चिह्न हटाएँ',
                'ex_save_next' => 'सहेजें व आगे', 'ex_submit' => 'जमा करें',
                'ex_palette' => 'प्रश्न पट',
                'ex_answered' => 'उत्तर दिया', 'ex_not_answered' => 'अनुत्तरित',
                'ex_marked' => 'चिह्नित', 'ex_ans_marked' => 'उत्तर + चिह्न',
                'ex_lang_en' => 'English', 'ex_lang_hi' => 'हिंदी',
                'ex_lang_label' => 'भाषा',
                'ex_translate_q' => 'हिंदी में दिखाएँ', 'ex_translate_q_back' => 'English में दिखाएँ',
                'ex_submit_confirm' => 'क्या आप वाकई परीक्षा जमा करना चाहते हैं? जमा करने के बाद उत्तर नहीं बदले जा सकते।',
                'ex_violation' => 'उल्लंघन पकड़ा गया — यह दर्ज किया जा रहा है।',
                'ex_qtype_mcq' => 'बहुविकल्पीय', 'ex_qtype_multi' => 'बहु-चयन',
                'ex_qtype_tf' => 'सत्य / असत्य', 'ex_qtype_sa' => 'संक्षिप्त उत्तर', 'ex_qtype_num' => 'संख्यात्मक',
                'ex_true' => 'सत्य', 'ex_false' => 'असत्य',
                'ex_no_hi' => '(इस प्रश्न का हिंदी अनुवाद उपलब्ध नहीं है)',
            ],
        ];
    }
    $L = lang();
    return $D[$L][$key] ?? $D['en'][$key] ?? $key;
}
