<?php
// Bilingual dictionary (English + Hindi) for PUBLIC pages
// Admin console remains English.

function lang(): string {
    if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'hi'], true)) {
        $_SESSION['lang'] = $_GET['lang'];
    }
    return $_SESSION['lang'] ?? 'en';
}

function t(string $key): string {
    static $D = null;
    if ($D === null) {
        $D = [
            'en' => [
                // Branding and portal chrome
                'gov_in' => 'GOVERNMENT OF INDIA', 'gov_in_hi' => 'भारत सरकार',
                'mod' => 'Ministry of Defence · Public Sector Undertaking',
                'brand' => 'Bharat Electronics Limited',
                'brand_unit' => 'KOTDWAR · ASSESSMENT PORTAL',
                'system_online' => 'System Online',
                'lang_toggle' => 'हिंदी',
                'bar_portal' => 'ONLINE EXAMINATION & ASSESSMENT PORTAL · BEL KOTDWAR UNIT',

                // Public landing page
                'hero_title' => 'Secure online assessment, built for BEL Kotdwar.',
                'hero_sub' => 'Conduct fair, lockdown-secured exams for candidates and trainees with proctoring, violation logs, and instant evaluation — exactly like a real test centre.',
                'cta_student' => 'Candidate / Student Login',
                'cta_admin' => 'Administrator Login',
                'cta_note' => 'New candidates do not register here. Accounts are issued by the BEL administrator.',
                'about_h' => 'About Bharat Electronics Limited',
                'about_p1' => 'Bharat Electronics Limited (BEL) is a Navratna Public Sector Undertaking under the Ministry of Defence, Government of India, established in 1954 and headquartered in Bengaluru.',
                'about_p2' => 'BEL has nine manufacturing units across India — Bengaluru, Ghaziabad, Pune, Hyderabad, Machilipatnam, Chennai, Panchkula, Navi Mumbai and Kotdwar (Uttarakhand).',
                'quick_facts' => 'Quick Facts',
                'feat1_h' => 'Lockdown Browser', 'feat1_t' => 'Fullscreen, tab-switch detection, copy/paste blocked, auto-submit on repeated violations.',
                'feat2_h' => 'Live Proctoring', 'feat2_t' => 'Webcam preview and time-stamped violation logs visible to administrators.',
                'feat3_h' => 'Audit Trail', 'feat3_t' => 'Every answer and event is timestamped. Reviewers see what was selected and when.',
                'footer_auth' => 'For authorised use only · सर्वाधिकार सुरक्षित',
                'footer_enterprise' => 'A Government of India Enterprise · Kotdwar Unit',

                // Login pages
                'sl_title' => 'Candidate Login', 'sl_sub' => 'Login using your Roll Number / Staff ID, Date of Birth, and password.',
                'sl_id' => 'Roll Number / Staff ID', 'sl_dob' => 'Date of Birth', 'sl_pwd' => 'Password',
                'sl_submit' => 'Sign In', 'sl_back' => 'Back', 'sl_forgot' => 'Forgot password?',
                'al_title' => 'Administrator Login', 'al_sub' => 'Restricted — for BEL Kotdwar exam administrators only.',
                'al_id' => 'Email',

                // Student dashboard
                'sd_title' => 'Available Examinations', 'sd_sub' => 'Read the instructions carefully before starting any exam.',
                'sd_my_results' => 'My Results', 'sd_logout' => 'Logout',
                'sd_duration' => 'Duration', 'sd_questions' => 'Questions', 'sd_attempts_left' => 'Attempts left',
                'sd_view_instructions' => 'View Instructions', 'sd_join' => 'Join', 'sd_join_now' => 'Join Exam', 'sd_start_exam' => 'Start Exam', 'sd_join_window_closed' => 'Join window closed', 'sd_join_window_closes_in' => 'Join window closes in', 'sd_currently_ongoing' => 'Currently ongoing', 'sd_welcome' => 'Welcome',
                'sd_closed' => 'Closed', 'sd_upcoming' => 'Upcoming', 'sd_active' => 'Active',
                'sd_no_exams' => 'No exams scheduled yet.',
                'sd_candidate_portal' => 'Candidate Portal',
                'sd_kotdwar_unit' => 'Kotdwar Unit',
                'sd_mode_join_window' => 'Join window %d min',
                'sd_mode_direct_start' => 'Direct start',
                'sd_visibility_join' => 'You can start only during the join window before the exam begins.',
                'sd_visibility_direct' => 'You can join anytime while the exam is active until the end time.',
                'sd_join_window_enabled' => 'Join window is enabled for this exam.',
                'sd_join_window_disabled' => 'Join window is disabled. Students can enter during the active exam period.',
                'sd_window_label' => 'Window',
                'sd_max_attempts' => 'Max Attempts',
                'sd_no_questions' => 'No Questions',
                'sd_exam_controller_note' => 'No examinations have been assigned to your account yet. Please contact the BEL Kotdwar Examination Controller.',

                // Instruction page
                'in_title' => 'Examination Instructions', 'in_begin' => 'Confirm & Begin Exam',
                'in_agree' => 'I have read all instructions and understand violations will be recorded.',
                'in_exam_code_label' => 'Exam Code',
                'in_exam_type_join' => 'Official Join Window Exam',
                'in_exam_type_direct' => 'Official Direct Start Exam',
                'in_intro_join' => 'Official monitored examination. Keep this page open, remain ready for the join window, and wait for the system to redirect you to the test interface.',
                'in_intro_direct' => 'Official monitored examination. Read every instruction carefully, complete the declaration, and begin only when you are ready to maintain exam discipline throughout the session.',
                'in_notice_title' => 'Official Candidate Notice',
                'in_notice_body' => 'This is an official monitored examination. Candidates must keep this page open, remain attentive to the join-window timer, and follow all instructions issued by the system and invigilating authority.',
                'in_office_title' => 'Office Instructions',
                'in_office_preamble' => 'The following exam-specific conditions are issued for compliance during the examination session.',
                'in_compliance_title' => 'Mandatory compliance notice',
                'in_compliance_body' => 'This assessment is monitored. Read all rules, keep your face visible, maintain exam discipline, and do not attempt any unauthorised action during the session.',
                'in_declaration_title' => 'Candidate Declaration',
                'in_declaration_body' => 'I hereby declare that I am the genuine registered candidate for this examination, that I have read and understood the instructions, and that I shall comply with all examination rules, monitoring requirements, and conduct standards until the session is completed.',
                'in_agree_detail' => 'I confirm that I have read the official notice and declaration above and I agree to abide by all examination rules.',
                'in_overlay_preparing' => 'Preparing to start',
                'in_overlay_countdown_badge' => 'Live Countdown',
                'in_overlay_countdown_msg' => 'The system will redirect you to the examination window when the join timer reaches the start time. Keep this page active until the redirect occurs.',
                'in_overlay_direct_msg' => 'Click Start Exam only after you have read all instructions and are ready to begin the monitored session in fullscreen mode.',
                'in_overlay_start' => 'Start Exam',
                'in_overlay_cancel' => 'Cancel',
                'in_overlay_hint_countdown' => 'The countdown is synchronized with the exam schedule. Remain on this page until the system redirects you.',
                'in_overlay_hint_direct' => 'This exam does not use a join-window countdown.',
                'in_guidance_1_title' => 'Candidate Verification',
                'in_guidance_1_body' => 'Ensure that your registered details are correct before starting. The examination shall be treated as <strong>personal and non-transferable</strong>. Any mismatch or impersonation may lead to cancellation.',
                'in_guidance_2_title' => 'Secure Examination Environment',
                'in_guidance_2_body' => 'Take the exam from a quiet, well-lit, and uninterrupted location. No unauthorised person should be present near your desk, camera, or screen during the test.',
                'in_guidance_3_title' => 'Browser Discipline',
                'in_guidance_3_body' => 'Do not refresh the page, open new tabs, use split-screen mode, access external websites, or switch applications. Such actions may be recorded as a violation under the proctoring policy.',
                'in_guidance_4_title' => 'Webcam and Monitoring',
                'in_guidance_4_body' => 'Keep your face visible in the webcam frame at all times. Ensure proper lighting and stable internet connectivity so that monitoring remains clear throughout the session.',
                'in_guidance_5_title' => 'Question Navigation',
                'in_guidance_5_body' => 'Read each question carefully before answering. You may move between questions, review responses, and return later if the question palette remains available in the exam interface.',
                'in_guidance_6_title' => 'Answer Submission',
                'in_guidance_6_body' => 'Save each answer before moving to the next question wherever applicable. Final submission should be completed only after verifying your responses and remaining time.',
                'in_guidance_7_title' => 'Violation Policy',
                'in_guidance_7_body' => 'Any prohibited activity, repeated tab switching, or suspicious behaviour may be logged. After '.MAX_VIOLATIONS.' violations, the system will <strong>auto-submit</strong> the test and record the incident.',
                'in_guidance_8_title' => 'Completion and Exit',
                'in_guidance_8_body' => 'Remain on the exam page until the test is fully submitted. Do not close the browser window abruptly, as incomplete submission may affect your result status.',

                // Results and recovery
                'rs_title' => 'My Results', 'rs_exam' => 'Exam', 'rs_attempt' => 'Attempt', 'rs_score' => 'Score', 'rs_submitted' => 'Submitted', 'rs_none' => 'No attempts yet.',
                'fg_title' => 'Forgot Password', 'fg_get' => 'Get Reset Token', 'fg_reset' => 'Reset Password',
                'fg_token' => 'Reset Token', 'fg_newpwd' => 'New Password (min 6)',

                // ----- Take-Exam screen (offline, no Google Translate) -----
                'ex_attempt' => 'Attempt', 'ex_question' => 'Question', 'ex_marks' => 'marks',
                'ex_start_fs_title' => 'Start in Fullscreen',
                'ex_start_fs_hint' => 'Click the button below to enter fullscreen and begin the lockdown exam session.',
                'ex_start_fs_btn' => 'Enter Fullscreen & Start Exam',
                'ex_live' => 'LIVE',
                'ex_prev' => 'Previous', 'ex_mark' => 'Mark for Review', 'ex_unmark' => 'Unmark Review',
                'ex_save_next' => 'Save & Next', 'ex_submit' => 'Submit',
                'ex_palette' => 'Question Palette',
                'ex_answered' => 'Answered', 'ex_not_answered' => 'Not Ans.',
                'ex_marked' => 'Marked', 'ex_ans_marked' => 'Ans+Mark',
                'ex_lang_en' => 'English', 'ex_lang_hi' => 'हिंदी',
                'ex_lang_label' => 'Language',
                'ex_translate_q' => 'Show in हिंदी', 'ex_translate_q_back' => 'Show in English',
                'ex_submit_confirm' => 'Are you sure you want to submit the exam? You cannot change answers after submitting.',
                'ex_violation' => 'Violation detected — this is being recorded.',
                'ex_qtype_mcq' => 'Multiple Choice', 'ex_qtype_multi' => 'Multi Select',
                'ex_qtype_tf' => 'True / False', 'ex_qtype_sa' => 'Short Answer', 'ex_qtype_num' => 'Numeric',
                'ex_true' => 'True', 'ex_false' => 'False',
                'ex_no_hi' => '(Hindi translation not available for this question)',
            ],
            'hi' => [
                // Branding and portal chrome
                'gov_in' => 'भारत सरकार', 'gov_in_hi' => 'GOVERNMENT OF INDIA',
                'mod' => 'रक्षा मंत्रालय · सार्वजनिक उपक्रम',
                'brand' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड',
                'brand_unit' => 'कोटद्वार · मूल्यांकन पोर्टल',
                'system_online' => 'सिस्टम ऑनलाइन',
                'lang_toggle' => 'English',
                'bar_portal' => 'ऑनलाइन परीक्षा एवं मूल्यांकन पोर्टल · BEL कोटद्वार इकाई',

                // Public landing page
                'hero_title' => 'BEL कोटद्वार के लिए सुरक्षित ऑनलाइन मूल्यांकन।',
                'hero_sub' => 'अभ्यर्थियों व प्रशिक्षुओं के लिए लॉकडाउन-सुरक्षित परीक्षा, प्रॉक्टरिंग, उल्लंघन लॉग और तत्काल मूल्यांकन।',
                'cta_student' => 'अभ्यर्थी / विद्यार्थी लॉगिन',
                'cta_admin' => 'प्रशासक लॉगिन',
                'cta_note' => 'नए अभ्यर्थी यहाँ पंजीकरण नहीं करते। खाते BEL प्रशासक द्वारा जारी किए जाते हैं।',
                'about_h' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड के बारे में',
                'about_p1' => 'भारत इलेक्ट्रॉनिक्स लिमिटेड (BEL) भारत सरकार के रक्षा मंत्रालय के अधीन नवरत्न सार्वजनिक उपक्रम है, स्थापना 1954, मुख्यालय बेंगलुरु।',
                'about_p2' => 'BEL की भारत में नौ विनिर्माण इकाइयाँ हैं — बेंगलुरु, गाज़ियाबाद, पुणे, हैदराबाद, मछलीपट्टनम, चेन्नई, पंचकुला, नवी मुंबई तथा कोटद्वार।',
                'quick_facts' => 'मुख्य तथ्य',
                'feat1_h' => 'लॉकडाउन ब्राउज़र', 'feat1_t' => 'पूर्ण स्क्रीन, टैब-स्विच पहचान, कॉपी/पेस्ट निष्क्रिय, उल्लंघन पर स्वतः जमा।',
                'feat2_h' => 'लाइव प्रॉक्टरिंग', 'feat2_t' => 'वेबकैम व समय-मुद्रित उल्लंघन लॉग प्रशासकों हेतु।',
                'feat3_h' => 'ऑडिट ट्रेल', 'feat3_t' => 'प्रत्येक उत्तर व घटना समय-मुद्रित।',
                'footer_auth' => 'केवल अधिकृत उपयोग हेतु · सर्वाधिकार सुरक्षित',
                'footer_enterprise' => 'भारत सरकार का उपक्रम · कोटद्वार इकाई',

                // Login pages
                'sl_title' => 'अभ्यर्थी लॉगिन', 'sl_sub' => 'अपनी रोल/स्टाफ़ आईडी, जन्म तिथि तथा पासवर्ड से लॉगिन करें।',
                'sl_id' => 'रोल/स्टाफ़ आईडी / उपयोगकर्ता नाम', 'sl_dob' => 'जन्म तिथि', 'sl_pwd' => 'पासवर्ड',
                'sl_submit' => 'लॉगिन करें', 'sl_back' => 'वापस', 'sl_forgot' => 'पासवर्ड भूल गए?',
                'al_title' => 'प्रशासक लॉगिन', 'al_sub' => 'प्रतिबंधित क्षेत्र — केवल BEL प्रशासकों हेतु।',
                'al_id' => 'ईमेल / उपयोगकर्ता नाम',

                // Student dashboard
                'sd_title' => 'उपलब्ध परीक्षाएँ', 'sd_sub' => 'कोई भी परीक्षा शुरू करने से पहले निर्देश ध्यानपूर्वक पढ़ें।',
                'sd_my_results' => 'मेरे परिणाम', 'sd_logout' => 'लॉगआउट',
                'sd_duration' => 'अवधि', 'sd_questions' => 'प्रश्न', 'sd_attempts_left' => 'शेष प्रयास',
                'sd_view_instructions' => 'निर्देश देखें', 'sd_join' => 'जॉइन', 'sd_join_now' => 'परीक्षा में शामिल हों', 'sd_start_exam' => 'परीक्षा प्रारंभ करें', 'sd_join_window_closed' => 'जॉइन विंडो बंद हो गई है', 'sd_join_window_closes_in' => 'जॉइन विंडो समाप्त होगी', 'sd_currently_ongoing' => 'वर्तमान में चल रही', 'sd_welcome' => 'स्वागत है',
                'sd_closed' => 'बंद', 'sd_upcoming' => 'आगामी', 'sd_active' => 'सक्रिय',
                'sd_no_exams' => 'अभी कोई परीक्षा निर्धारित नहीं है।',
                'sd_candidate_portal' => 'अभ्यर्थी पोर्टल',
                'sd_kotdwar_unit' => 'कोटद्वार इकाई',
                'sd_mode_join_window' => 'जॉइन विंडो %d मिनट',
                'sd_mode_direct_start' => 'सीधा प्रारंभ',
                'sd_visibility_join' => 'आप केवल परीक्षा प्रारंभ होने से पहले जॉइन विंडो के दौरान ही शुरू कर सकते हैं।',
                'sd_visibility_direct' => 'परीक्षा सक्रिय रहने तक आप अंतिम समय तक किसी भी समय शामिल हो सकते हैं।',
                'sd_join_window_enabled' => 'इस परीक्षा के लिए जॉइन विंडो सक्षम है।',
                'sd_join_window_disabled' => 'जॉइन विंडो निष्क्रिय है। छात्र सक्रिय परीक्षा अवधि में प्रवेश कर सकते हैं।',
                'sd_window_label' => 'विंडो',
                'sd_max_attempts' => 'अधिकतम प्रयास',
                'sd_no_questions' => 'कोई प्रश्न नहीं',
                'sd_exam_controller_note' => 'आपके खाते के लिए अभी कोई परीक्षा आवंटित नहीं की गई है। कृपया BEL कोटद्वार परीक्षा नियंत्रक से संपर्क करें।',

                // Instruction page
                'in_title' => 'परीक्षा निर्देश', 'in_begin' => 'पुष्टि करें व प्रारंभ करें',
                'in_agree' => 'मैंने सभी निर्देश पढ़ लिए हैं और समझता/समझती हूँ कि उल्लंघन दर्ज किए जाएँगे।',
                'in_exam_code_label' => 'परीक्षा कोड',
                'in_exam_type_join' => 'आधिकारिक जॉइन विंडो परीक्षा',
                'in_exam_type_direct' => 'आधिकारिक सीधा प्रारंभ परीक्षा',
                'in_intro_join' => 'यह एक आधिकारिक निगरानी-युक्त परीक्षा है। यह पृष्ठ खुला रखें, जॉइन विंडो के लिए तैयार रहें, और सिस्टम द्वारा परीक्षा इंटरफेस पर रीडायरेक्ट किए जाने की प्रतीक्षा करें।',
                'in_intro_direct' => 'यह एक आधिकारिक निगरानी-युक्त परीक्षा है। सभी निर्देश ध्यानपूर्वक पढ़ें, घोषणा पूर्ण करें, और केवल तभी प्रारंभ करें जब आप पूरे सत्र में परीक्षा अनुशासन बनाए रखने के लिए तैयार हों।',
                'in_notice_title' => 'आधिकारिक अभ्यर्थी सूचना',
                'in_notice_body' => 'यह एक आधिकारिक, निगरानी-युक्त परीक्षा है। अभ्यर्थी को यह पृष्ठ खुला रखना होगा, जॉइन विंडो टाइमर पर ध्यान रखना होगा, तथा सिस्टम और निरीक्षण प्राधिकारी द्वारा जारी सभी निर्देशों का पालन करना होगा।',
                'in_office_title' => 'कार्यालयीय निर्देश',
                'in_office_preamble' => 'निम्नलिखित परीक्षा-विशिष्ट शर्तें परीक्षा सत्र के दौरान अनुपालन हेतु जारी की जाती हैं।',
                'in_compliance_title' => 'अनिवार्य अनुपालन सूचना',
                'in_compliance_body' => 'यह मूल्यांकन निगरानी-युक्त है। सभी नियम पढ़ें, अपना चेहरा स्पष्ट रखें, परीक्षा अनुशासन बनाए रखें, तथा सत्र के दौरान किसी भी अनधिकृत कार्य का प्रयास न करें।',
                'in_declaration_title' => 'अभ्यर्थी घोषणा',
                'in_declaration_body' => 'मैं एतद् द्वारा घोषित करता/करती हूँ कि मैं इस परीक्षा का वास्तविक पंजीकृत अभ्यर्थी हूँ, मैंने निर्देश पढ़ और समझ लिए हैं, तथा परीक्षा पूर्ण होने तक सभी नियमों, निगरानी आवश्यकताओं और आचरण मानकों का पालन करूँगा/करूँगी।',
                'in_agree_detail' => 'मैं यह पुष्टि करता/करती हूँ कि मैंने उपरोक्त आधिकारिक सूचना एवं घोषणा पढ़ ली है और मैं सभी परीक्षा नियमों का पालन करने के लिए सहमत हूँ।',
                'in_overlay_preparing' => 'प्रारंभ की तैयारी',
                'in_overlay_countdown_badge' => 'लाइव काउंटडाउन',
                'in_overlay_countdown_msg' => 'जॉइन टाइमर प्रारंभ समय पर पहुँचते ही सिस्टम आपको परीक्षा विंडो पर रीडायरेक्ट करेगा। रीडायरेक्ट होने तक यह पृष्ठ सक्रिय रखें।',
                'in_overlay_direct_msg' => 'सभी निर्देश पढ़ने और पूर्ण स्क्रीन में निगरानी-युक्त सत्र प्रारंभ करने के लिए तैयार होने के बाद ही "Start Exam" पर क्लिक करें।',
                'in_overlay_start' => 'परीक्षा प्रारंभ करें',
                'in_overlay_cancel' => 'रद्द करें',
                'in_overlay_hint_countdown' => 'यह उलटी गिनती परीक्षा समय-सारिणी के अनुरूप है। सिस्टम द्वारा रीडायरेक्ट किए जाने तक इसी पृष्ठ पर बने रहें।',
                'in_overlay_hint_direct' => 'इस परीक्षा में जॉइन विंडो काउंटडाउन का उपयोग नहीं किया गया है।',
                'in_guidance_1_title' => 'अभ्यर्थी सत्यापन',
                'in_guidance_1_body' => 'परीक्षा प्रारंभ करने से पहले अपने पंजीकृत विवरण सही होने की पुष्टि करें। यह परीक्षा <strong>व्यक्तिगत एवं अपरिवर्तनीय</strong> मानी जाएगी। किसी भी प्रकार की विसंगति या अनुकरण के कारण परीक्षा निरस्त की जा सकती है।',
                'in_guidance_2_title' => 'सुरक्षित परीक्षा वातावरण',
                'in_guidance_2_body' => 'परीक्षा शांत, पर्याप्त रोशनी वाले और बिना व्यवधान वाले स्थान से दें। परीक्षा के दौरान आपके डेस्क, कैमरा या स्क्रीन के पास कोई अनधिकृत व्यक्ति उपस्थित नहीं होना चाहिए।',
                'in_guidance_3_title' => 'ब्राउज़र अनुशासन',
                'in_guidance_3_body' => 'पृष्ठ को रिफ्रेश न करें, नए टैब न खोलें, स्प्लिट-स्क्रीन का उपयोग न करें, बाहरी वेबसाइटों तक न जाएँ, तथा एप्लिकेशन न बदलें। ऐसे कार्य प्रॉक्टरिंग नीति के अंतर्गत उल्लंघन के रूप में दर्ज किए जा सकते हैं।',
                'in_guidance_4_title' => 'वेबकैम एवं निगरानी',
                'in_guidance_4_body' => 'अपने चेहरे को पूरे समय वेबकैम फ्रेम में स्पष्ट रखें। पर्याप्त प्रकाश और स्थिर इंटरनेट कनेक्शन सुनिश्चित करें ताकि पूरे सत्र में निगरानी स्पष्ट बनी रहे।',
                'in_guidance_5_title' => 'प्रश्न नेविगेशन',
                'in_guidance_5_body' => 'प्रत्येक प्रश्न को उत्तर देने से पहले ध्यानपूर्वक पढ़ें। आप प्रश्नों के बीच जा सकते हैं, उत्तरों की समीक्षा कर सकते हैं, और यदि प्रश्न पैलेट उपलब्ध हो तो बाद में वापस आ सकते हैं।',
                'in_guidance_6_title' => 'उत्तर जमा करना',
                'in_guidance_6_body' => 'जहाँ आवश्यक हो, अगले प्रश्न पर जाने से पहले प्रत्येक उत्तर को सहेजें। अंतिम जमा केवल उत्तरों तथा शेष समय की जाँच के बाद ही करें।',
                'in_guidance_7_title' => 'उल्लंघन नीति',
                'in_guidance_7_body' => 'किसी भी निषिद्ध गतिविधि, बार-बार टैब बदलने, या संदिग्ध व्यवहार को लॉग किया जा सकता है। '.MAX_VIOLATIONS.' उल्लंघनों के बाद सिस्टम परीक्षा को <strong>स्वतः जमा</strong> कर देगा और घटना दर्ज करेगा।',
                'in_guidance_8_title' => 'समापन एवं प्रस्थान',
                'in_guidance_8_body' => 'परीक्षा पूर्ण रूप से जमा होने तक इसी पृष्ठ पर बने रहें। ब्राउज़र विंडो को अचानक बंद न करें, क्योंकि अपूर्ण जमा आपकी परिणाम स्थिति को प्रभावित कर सकता है।',

                // Results and recovery
                'rs_title' => 'मेरे परिणाम', 'rs_exam' => 'परीक्षा', 'rs_attempt' => 'प्रयास', 'rs_score' => 'अंक', 'rs_submitted' => 'जमा किया', 'rs_none' => 'अभी कोई प्रयास नहीं।',
                'fg_title' => 'पासवर्ड भूल गए', 'fg_get' => 'रीसेट टोकन प्राप्त करें', 'fg_reset' => 'पासवर्ड रीसेट करें',
                'fg_token' => 'रीसेट टोकन', 'fg_newpwd' => 'नया पासवर्ड (न्यूनतम 6)',

                // ----- परीक्षा स्क्रीन (ऑफ़लाइन / इंट्रानेट के लिए) -----
                'ex_attempt' => 'प्रयास', 'ex_question' => 'प्रश्न', 'ex_marks' => 'अंक',
                'ex_start_fs_title' => 'पूर्ण स्क्रीन में प्रारंभ करें',
                'ex_start_fs_hint' => 'परीक्षा प्रारंभ करने के लिए नीचे दिए बटन पर क्लिक करें और पूर्ण स्क्रीन में प्रवेश करें।',
                'ex_start_fs_btn' => 'पूर्ण स्क्रीन में जाएँ और परीक्षा प्रारंभ करें',
                'ex_live' => 'लाइव',
                'ex_prev' => 'पिछला', 'ex_mark' => 'समीक्षा हेतु चिह्नित करें', 'ex_unmark' => 'चिह्न हटाएँ',
                'ex_save_next' => 'सहेजें व आगे', 'ex_submit' => 'जमा करें',
                'ex_palette' => 'प्रश्न पट',
                'ex_answered' => 'उत्तर दिया', 'ex_not_answered' => 'अनुत्तरित',
                'ex_marked' => 'चिह्नित', 'ex_ans_marked' => 'उत्तर + चिह्न',
                'ex_lang_en' => 'English', 'ex_lang_hi' => 'हिंदी',
                'ex_lang_label' => 'भाषा',
                'ex_translate_q' => 'हिंदी में दिखाएँ', 'ex_translate_q_back' => 'English में दिखाएँ',
                'ex_submit_confirm' => 'क्या आप वाकई परीक्षा जमा करना चाहते हैं? जमा करने के बाद उत्तर नहीं बदले जा सकते।',
                'ex_violation' => 'उल्लंघन पकड़ा गया — यह दर्ज किया जा रहा है।',
                'ex_qtype_mcq' => 'बहुविकल्पीय', 'ex_qtype_multi' => 'बहु-चयन',
                'ex_qtype_tf' => 'सत्य / असत्य', 'ex_qtype_sa' => 'संक्षिप्त उत्तर', 'ex_qtype_num' => 'संख्यात्मक',
                'ex_true' => 'सत्य', 'ex_false' => 'असत्य',
                'ex_no_hi' => '(इस प्रश्न का हिंदी अनुवाद उपलब्ध नहीं है)',
            ],
        ];
    }
    $L = lang();
    return $D[$L][$key] ?? $D['en'][$key] ?? $key;
}
